### ISSUE TITLE
Bot needs to be verified to be invited to servers

### ISSUE THREAD

**Issue by ElijahKujo** [oct2pus/jadebot#9]
![image](https://user-images.githubusercontent.com/66164098/154273307-b1783aea-40f5-47c4-8332-794df1593dad.png)

**Comment by oct2pus** [comment]
way way late
i am not verifying the bot to be clear.

this is functionally abandoned, I do not find joy in discord bot development anymore and I honestly hate the idea of a verification system. I intend to keep her running as long as I can but I don't intend to really improve her at all.
